apiVersion: v1
kind: Service
metadata:
  name: mail-system-postfix-smtp
  labels:
    app: mail-system
spec:
  type: LoadBalancer
  ports:
    - port: 25
      targetPort: 25
      protocol: TCP
      name: smtp
  selector:
    service: mail-system-postfix
---
apiVersion: v1
kind: Service
metadata:
  name: mail-system-postfix-submission
  labels:
    app: mail-system
spec:
  type: LoadBalancer
  ports:
    - port: 587
      targetPort: 587
      protocol: TCP
      name: smtp
  selector:
    service: mail-system-postfix
