apiVersion: apps/v1
kind: Deployment
metadata:
  name: mail-system-postfix
  labels:
    app: mail-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mail-system
  template:
    metadata:
      annotations:
        deployedAt: "{{ date "20060102150405" .Release.Time }}"
      labels:
        app: mail-system
        service: mail-system-postfix
    spec:
      automountServiceAccountToken: false
      containers:
        - name: postfix
          image: cromega/mail-system:latest
          imagePullPolicy: Always
          command: ["/start.sh", "postfix"]
          env:
            - name: SUBLIMIA_MAIL_DOMAINS
              value: sublimia.nl
            - name: SMTP_RELAY_CONFIG
              value: "{{ .Values.smtp_relay_config }}"
          ports:
            - name: smtp
              containerPort: 25
              protocol: TCP
            - name: submission
              containerPort: 587
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - /check.sh
                - "25 587"
            initialDelaySeconds: 30
          startupProbe:
            exec:
              command:
                - /check.sh
                - "25 587"
            failureThreshold: 30
            periodSeconds: 10
          volumeMounts:
            - name: tls-cert
              mountPath: /etc/sublimia/ssl/
              readOnly: true
      volumes:
        - name: tls-cert
          secret:
            secretName: wildcard-certificate
